#!/bin/bash
rm -rf /tmp/pricing-sandbox
mkdir -p /tmp/pricing-sandbox
chown paperclip:paperclip /tmp/pricing-sandbox
su - paperclip -c 'rm -f /home/paperclip/.openclaw/agents/main/sessions/*.lock'

su - paperclip -c 'env OPENAI_API_KEY="'"$OPENAI_API_KEY"'" GITHUB_TOKEN="'"$GITHUB_TOKEN"'" /usr/bin/openclaw agent --agent main -m "Go to /tmp/pricing-sandbox. You MUST execute strictly autonomously: 1. Run exactly: git clone https://github.com/Abhishek-AMK/zero-human-sandbox.git . 2. Run exactly: git checkout -b feature-pricing. 3. Create a physical file pricing.html containing a gorgeous, responsive HTML/CSS pricing table with 3 tiers. 4. Run exactly: git add pricing.html 5. Run exactly: git commit -m \"Added pricing component\". 6. Run exactly: git push -u origin feature-pricing. 7. Run exactly: gh pr create --head feature-pricing --title \"Feature: Pricing Component\" --body \"Autonomously generated by the Architect Agent.\" 8. Exit cleanly."'
